#!/usr/bin/env bash

# Prerequisites
# https://github.com/eth0izzle/shhgit
# npm

KEYWORD=$1

# CHANGE THE LOCAL DIR FOR WHATEVER YOU WANT.
LOCAL_DIR="/tmp/npm"

SHHGIT_CONFIG="$HOME/shhgit-config/"

mkdir -p $LOCAL_DIR
mkdir -p "${LOCAL_DIR}/${KEYWORD}"

# Search for npm packages with npmsearch.py .
echo "[-] Searching for NPM packages with the keyword '$KEYWORD'."

# Note: Change to `python` if you only have Python 3.
python3 ./npmsearch.py -s -q $KEYWORD > "${LOCAL_DIR}/${KEYWORD}/list.txt"

cd "${LOCAL_DIR}/${KEYWORD}"

cat "${LOCAL_DIR}/${KEYWORD}/list.txt" |\
	xargs -I {} sh -c "mkdir -p {} && /usr/local/bin/npm v {} dist.tarball | xargs curl -s | tar -xz -C {}"

RES_COUNT=$(ls | wc -l)
echo "[+] Found $RES_COUNT packages."

echo "[-] Scanning for secrets. Hold on.."

shhgit -config-path "$SHHGIT_CONFIG" -local .
